SM:AddTab("General Settings")
SM:Dropdown("Rune Type", "runeType", {"air", "water", "earth", "fire", "mind", "body", "nature", "astral", "cosmic", "blood", "chaos", "law", "death", "soul", "time"}, "air")
SM:Checkbox("Access to Astral altar?", "hasAccessToAstralAltar", false)
SM:Checkbox("Access to Death altar?", "hasAccessToDeathAltar", false)
SM:Checkbox("Access to Blood altar?", "hasAccessToBloodAltar", false)
SM:Checkbox("Access to Soul altar?", "hasAccessToSoulAltar", false)
SM:Checkbox("Access to Time altar?", "hasAccessToTimeAltar", false)
SM:Checkbox("Abyssal parasite?", "hasAbyssalParasite", false)
SM:Checkbox("Abyssal lurker?", "hasAbyssalLurker", false)
SM:Checkbox("Abyssal titan?", "hasAbyssalTitan", false)